import {
  Apple,
  Castle,
  Circle,
  Citrus,
  Cloud,
  Droplet,
  Flame,
  Flower2,
  Gem,
  Globe,
  Grape,
  Heart,
  Leaf,
  type LucideIcon,
  Mountain,
  Shield,
  Sparkles,
  Sprout,
  Sun,
  Trees,
  Triangle,
  Wind,
  Zap,
} from 'lucide-react';

export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  castle: Castle,
  circle: Circle,
  citrus: Citrus,
  cloud: Cloud,
  droplet: Droplet,
  flame: Flame,
  flower: Flower2,
  fruit: Apple,
  globe: Globe,
  grape: Grape,
  heart: Heart,
  herb: Sprout,
  honey: Sparkles,
  leaf: Leaf,
  mineral: Gem,
  mountain: Mountain,
  nut: Triangle,
  oak: Trees,
  shield: Shield,
  smoke: Wind,
  sparkles: Sparkles,
  spice: Flame,
  stone: Mountain,
  sun: Sun,
  triangle: Triangle,
  tropical: Citrus,
  zap: Zap,
  default: Grape,
};

export const getLucideIcon = (key?: string): LucideIcon =>
  LUCIDE_ICONS[key ?? 'default'] ?? LUCIDE_ICONS.default ?? Grape;
