#!/usr/bin/env python3
"""Bakes the 88 per-skin footer caps the web renders.

    python3 scripts/bake-footer-caps.py

**What this is.** `vinodex-ios/Sources/VinodexUI/ChassisCapArt.swift` re-inks
four drawn moulded caps at runtime, once per (stem, ink) pair, so twenty-two
chassis skins get twenty-two sets of buttons from one drawing. This script is
a port of that algorithm, run at build time, writing the whole matrix to disk.

**Why baked rather than re-inked in the browser.** Measured, not assumed. The
expensive half of the iOS pipeline is `fitCap` -- the silhouette flood fill,
the coverage distance transform and the glyph-region walk -- and its output is
*ink-independent*, so it could be baked to a mask and the runtime reduced to a
per-pixel HSV pass of about 20ms per skin change. That is affordable. It is
still the wrong trade here:

  - The web re-inks from a fixed 22-row colour table. There is no
    user-chosen colour, because there is no Device Workshop on this side, so
    a runtime pipeline would compute at every launch what is knowable once.
  - It would put ~250 lines of pixel code, a canvas and an async
    `createImageBitmap` seam into `DeviceLayout`, which every screen mounts.
  - It has to match `litFloor`, the glyph inversion, the `<= 0.06` outline
    clause and the coverage feather *exactly*, and any drift shows up as
    "the buttons look wrong on one skin" -- the failure mode this subsystem
    has had five times.

The numbers that settled it, generated by running this port over the full
matrix: 88 files at 192px palette-64 come to roughly 700KB, none over ~12KB,
and the service worker already runtime-caches art PNGs rather than precaching
them. First paint costs four caps for the active skin.

**When to revisit.** If the Device Workshop lands, the buttons axis offers 13
`PartColor` values and the matrix becomes 13 x 4 = 1,144 files on top of the
88. At that point pre-baking stops being viable and the runtime path wins.
That is the trigger; nothing smaller is.

**Why Python.** PIL, and the fact that the algorithm's authority --
`import-footer-art.py` and `ChassisCapArt.swift` -- is Python and Swift. Node
would need `sharp` or `canvas`, a new dependency for a script no gate runs.
The output is committed, so CI never executes this; only a human regenerating
the caps needs Python, exactly as on the iOS side.

**The output directory is NOT `art/footer/`.** That folder is mirrored from
iOS by `sync-shared.ps1`'s art leg with `/MIR`, which deletes anything the
source side does not have -- so 88 baked files written there would vanish on
the next sync. They go to `art/caps/`, which no leg mirrors.
"""

import hashlib
import io
import json
import os
import re
import sys
from collections import deque

try:
    import numpy as np
    from PIL import Image
except ImportError:  # pragma: no cover - a human running the script
    sys.exit("this script needs numpy and pillow: pip install numpy pillow")


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "web", "public", "art", "footer")
DST = os.path.join(ROOT, "web", "public", "art", "caps")
THEME = os.path.join(ROOT, "web", "src", "services", "theme.ts")
MANIFEST = os.path.join(DST, "manifest.json")

# The rendered size. The caps draw at 48 CSS px (`w-12`) and 56 at `md`, so at
# DPR 3 the largest real demand is 168px. 192 is the next sensible step above
# that; 128 is visibly soft on a 3x phone and 254 (the source) triples the
# bytes for pixels no display asks for.
OUTPUT_PX = 192

# ---------------------------------------------------------------------------
# The re-ink, ported from ChassisCapArt.swift. Constants are its constants and
# the names are kept so the two can be diffed by eye.
# ---------------------------------------------------------------------------

LIT_FLOOR = 0.55
GLYPH_VALUE = 0.60
GLYPH_INNER_REACH = 0.20
GLYPH_OUTER_LIMIT = 0.78
EDGE_FEATHER = 1.5
OUTLINE_CEILING = 0.06

# `lipBandTop` and the third `lipHex` ink are deliberately NOT ported. They
# still exist in the Swift, but 0.8.98 made every caller pass nil: the whole
# body re-inks in `cap.top`, so the lip is already the button colour. Anyone
# reading ChassisCapArt.swift cold would implement them.

STEMS = ("back", "home", "user", "settings")


def value_of(rgba):
    """Max channel, un-premultiplied. `ChassisCapLoader.value`."""
    a = np.maximum(rgba[..., 3].astype(np.float64) / 255, 0.001)
    return np.minimum(rgba[..., :3].max(axis=2) / 255 / a, 1.0)


def largest_opaque_component(opaque):
    """The moulded part: the largest four-connected run of opaque pixels.

    This is the whole silhouette rule since iOS 0.8.6 (B1) -- it removes the
    detached specks the stripped cast shadow left behind, and is shape-correct
    for a knurled cog as well as for a disc. The geodesic `outlineReach` trim
    that 0.8.7 added and 0.8.91 retired is not here and must not come back: it
    fired on exactly one of its four inputs and destroyed it.
    """
    h, w = opaque.shape
    seen = np.zeros_like(opaque, dtype=bool)
    best, best_size = None, 0
    for sy, sx in np.argwhere(opaque):
        if seen[sy, sx]:
            continue
        stack = [(sy, sx)]
        seen[sy, sx] = True
        region = []
        while stack:
            y, x = stack.pop()
            region.append((y, x))
            for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
                if 0 <= ny < h and 0 <= nx < w and opaque[ny, nx] and not seen[ny, nx]:
                    seen[ny, nx] = True
                    stack.append((ny, nx))
        if len(region) > best_size:
            best_size, best = len(region), region
    out = np.zeros_like(opaque, dtype=bool)
    if best:
        for y, x in best:
            out[y, x] = True
    return out


def fit_cap(rgba):
    """Measure one sprite once: coverage ramp and glyph mask, both ink-free."""
    h, w, _ = rgba.shape
    part = largest_opaque_component(rgba[..., 3] > 0)

    # Coverage: BFS distance from the outside of the part, ramped over
    # `edgeFeather`. The sprites have strictly binary alpha, so without this
    # every edge is an aliased staircase all the way to the screen.
    dist = np.full((h, w), np.iinfo(np.int32).max, dtype=np.int32)
    pad = np.pad(part, 1, constant_values=False)
    edge = part & ~(pad[:-2, 1:-1] & pad[2:, 1:-1] & pad[1:-1, :-2] & pad[1:-1, 2:])
    q = deque()
    for y, x in zip(*np.nonzero(edge)):
        dist[y, x] = 1
        q.append((y, x))
    while q:
        y, x = q.popleft()
        nxt = dist[y, x] + 1
        for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
            if 0 <= ny < h and 0 <= nx < w and part[ny, nx] and dist[ny, nx] > nxt:
                dist[ny, nx] = nxt
                q.append((ny, nx))
    coverage = np.zeros((h, w))
    coverage[part] = np.minimum(dist[part] / EDGE_FEATHER, 1.0)

    ys, xs = np.nonzero(part)
    cy, cx = ys.mean(), xs.mean()

    # The part's median outermost radius over 360 rays. A *scale*, not a
    # boundary -- nothing is clipped to it (0.8.6, B1).
    limit = max(w, h)
    radii = []
    for i in range(360):
        th = i * 2 * np.pi / 360
        dx, dy = np.cos(th), np.sin(th)
        r, last = 0.0, 0.0
        while r < limit:
            x = int(round(cx + r * dx))
            y = int(round(cy + r * dy))
            if 0 <= x < w and 0 <= y < h and part[y, x]:
                last = r
            r += 0.5
        radii.append(last)
    radius = max(sorted(radii)[180], 1)

    # The incised symbol: dark pixels grouped into connected regions, and a
    # region is the glyph when it *starts* inside `glyphInnerReach` and stays
    # inside `glyphOuterLimit`. Shape, not threshold -- the rim, bevel and
    # knurl are annuli that never reach the centre, and no pair of value
    # thresholds separates them because the two sets overlap in both
    # variables (0.8.6, B1).
    v = value_of(rgba)
    dark = part & (v > OUTLINE_CEILING) & (v < GLYPH_VALUE)
    is_glyph = np.zeros((h, w), dtype=bool)
    visited = np.zeros((h, w), dtype=bool)
    for sy, sx in zip(*np.nonzero(dark)):
        if visited[sy, sx]:
            continue
        stack = [(sy, sx)]
        visited[sy, sx] = True
        region = []
        min_r, max_r = float("inf"), 0.0
        while stack:
            y, x = stack.pop()
            region.append((y, x))
            d = ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5 / radius
            min_r, max_r = min(min_r, d), max(max_r, d)
            for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
                if 0 <= ny < h and 0 <= nx < w and dark[ny, nx] and not visited[ny, nx]:
                    visited[ny, nx] = True
                    stack.append((ny, nx))
        if min_r < GLYPH_INNER_REACH and max_r < GLYPH_OUTER_LIMIT:
            for y, x in region:
                is_glyph[y, x] = True

    return {"coverage": coverage, "is_glyph": is_glyph}


def hsv_of_css(colour):
    """`#rrggbb` or `rgba(r,g,b,a)` -> (h, s, v).

    The three smoke-plastic skins author their caps as `rgba(...)`. iOS's
    parser rejects those and falls through to a saturation of zero, which
    greys the cap -- its own note calls that "the honest failure, and the one
    a smoked shell wants anyway". This reads the channels properly, because it
    can: the result is the same neutral for a grey-blue smoke, and correct
    rather than accidental for the green and purple ones.
    """
    m = re.match(r"^#([0-9a-fA-F]{6})$", colour)
    if m:
        n = int(m.group(1), 16)
        r, g, b = (n >> 16) & 255, (n >> 8) & 255, n & 255
    else:
        m = re.match(r"^rgba?\(([^)]*)\)$", colour)
        if not m:
            return (0.0, 0.0, 1.0)
        parts = [p.strip() for p in m.group(1).split(",")]
        r, g, b = (int(float(p)) for p in parts[:3])
    mx, mn = max(r, g, b) / 255, min(r, g, b) / 255
    d = mx - mn
    if d == 0:
        hue = 0.0
    elif mx == r / 255:
        hue = (((g - b) / 255 / d) % 6) / 6
    elif mx == g / 255:
        hue = (((b - r) / 255 / d) + 2) / 6
    else:
        hue = (((r - g) / 255 / d) + 4) / 6
    return (hue, 0.0 if mx == 0 else d / mx, mx)


def hsv_to_rgb(h, s, v):
    c = v * s
    x = c * (1 - abs((h * 6) % 2 - 1))
    m = v - c
    sector = int(h * 6) % 6
    z = np.zeros_like(c) if hasattr(c, "shape") else 0.0
    table = {0: (c, x, z), 1: (x, c, z), 2: (z, c, x), 3: (z, x, c), 4: (x, z, c), 5: (c, z, x)}
    r, g, b = table[sector]
    return (r + m) * 255, (g + m) * 255, (b + m) * 255


def reink(rgba, shape, ink_hex, glyph_hex):
    """Keep each pixel's value, take the target's hue and saturation.

    The operation is "the same drawing, in a different colour", and the three
    clauses that make it correct are all load-bearing:

      - **The outline clause.** A pixel at or under `0.06` keeps its own
        colour. Near-black is *structure*: pushing a hue into the cel line
        would draw the cap's own edge in the skin's colour and lose the thing
        that separates the part from the shell behind it.
      - **`litFloor`.** "Keep each pixel's value" quietly meant a black button
        could not exist -- the sprite's face is drawn near-white, so an
        authored `#292524` rendered as the pastel of its own hue. Below the
        floor the face multiplies onto the ink's value. Above it the scale is
        exactly 1, so every bright livery is byte-identical to what iOS
        shipped from 0.8.2. The threshold sits in a measured gap no shipped
        ink occupies (bright bottom out at 0.714, dark top out at 0.478).
      - **The glyph inversion.** On a dark cap the incised symbol cannot stay
        an incision: a groove is darker than its face, and darker than
        near-black is nothing. It becomes print.
    """
    h, w, _ = rgba.shape
    body = hsv_of_css(ink_hex)
    ink = hsv_of_css(glyph_hex) if glyph_hex else body
    body_scale = body[2] if body[2] < LIT_FLOOR else 1.0
    invert = body[2] < LIT_FLOOR

    a = rgba[..., 3].astype(np.float64)
    cov = shape["coverage"]
    v = value_of(rgba)
    out_a = np.rint(a * cov)

    keep = (a > 0) & (cov > 0)
    outline = keep & (v <= OUTLINE_CEILING)
    glyph_px = keep & shape["is_glyph"] & ~outline
    body_px = keep & ~outline & ~glyph_px

    out = np.zeros((h, w, 4), dtype=np.float64)
    for ch in range(3):
        out[..., ch] = np.where(outline, np.rint(rgba[..., ch] * cov), 0)
    out[..., 3] = np.where(keep, out_a, 0)

    out_v = np.zeros((h, w))
    out_v[glyph_px] = np.clip(ink[2] * (1.05 - v[glyph_px]), 0, 1) if invert else v[glyph_px]
    out_v[body_px] = v[body_px] * body_scale

    for mask, target in ((glyph_px, ink), (body_px, body)):
        if not mask.any():
            continue
        r, g, b = hsv_to_rgb(target[0], target[1], out_v[mask])
        aa = out_a[mask]
        out[..., 0][mask] = r * aa / 255
        out[..., 1][mask] = g * aa / 255
        out[..., 2][mask] = b * aa / 255

    return np.clip(out, 0, 255).astype(np.uint8)



def unpremultiply(rgba):
    """Undo `reink`'s premultiplication before the pixels become a PNG.

    `reink` is a faithful port of the Swift, and the Swift renders into a
    `CGContext` declared `premultipliedLast` -- so its colour channels come out
    multiplied by alpha, and Core Graphics knows that. A PNG does not: the
    format is straight alpha, and a viewer compositing a premultiplied pixel
    multiplies by alpha a second time. A pixel at coverage `c` composites as
    `rgb * c^2` instead of `rgb * c`.

    Today the error is invisible and bounded: the only partial-coverage pixels
    are the `edgeFeather` ring, which is 1.5px of cel outline whose value is at
    or under 0.06, so the largest achievable difference is under 2/255. It is
    corrected anyway, and corrected *before* the LANCZOS resize rather than
    after -- a downscale mixes edge pixels into their neighbours, so resizing
    premultiplied data spreads the error inward across a much wider band than
    the ring it started in, which is exactly how a harmless rounding difference
    becomes a visible dark fringe if the feather ever widens or the art gains a
    genuinely translucent region.
    """
    out = rgba.astype(np.float64)
    a = out[..., 3:4]
    with np.errstate(divide="ignore", invalid="ignore"):
        straight = np.where(a > 0, out[..., :3] * 255.0 / np.maximum(a, 1e-9), 0.0)
    out[..., :3] = np.clip(np.rint(straight), 0, 255)
    return out.astype(np.uint8)


# ---------------------------------------------------------------------------
# The colour table, read out of theme.ts
# ---------------------------------------------------------------------------

def read_cap_table():
    """Parse `SKIN_CAP` and `SKIN_CAP_SET` out of `theme.ts`.

    Parsed rather than duplicated. A second copy of a 22-row colour table is
    the thing `footerCap()` exists to prevent, and `capsManifest.test.ts`
    re-derives the table's hash from the TypeScript so a drift between the two
    fails a gate rather than showing up as one skin's buttons being stale.
    """
    src = io.open(THEME, encoding="utf-8").read()

    def caps_in(block):
        out = {}
        for m in re.finditer(
            r"(\w+):\s*\{\s*top:\s*'([^']+)',\s*bottom:\s*'([^']+)',\s*edge:\s*'([^']+)',\s*glyph:\s*'([^']+)'\s*\}",
            block,
        ):
            out[m.group(1)] = {
                "top": m.group(2), "bottom": m.group(3),
                "edge": m.group(4), "glyph": m.group(5),
            }
        return out

    def block_after(name):
        i = src.index(name)
        j = src.index("{", i)
        depth, k = 0, j
        while k < len(src):
            if src[k] == "{":
                depth += 1
            elif src[k] == "}":
                depth -= 1
                if depth == 0:
                    return src[j:k + 1]
            k += 1
        raise SystemExit("unbalanced braces after " + name)

    skin_cap = caps_in(block_after("const SKIN_CAP: Record<ChassisSkinId, ChassisCap>"))
    set_block = block_after("const SKIN_CAP_SET:")

    sets = {}
    for m in re.finditer(r"(\w+):\s*\{\s*(back:.*?)\n  \},", set_block, re.S):
        sets[m.group(1)] = caps_in(m.group(2))

    table = {}
    for skin, cap in skin_cap.items():
        table[skin] = {kind: sets.get(skin, {}).get(kind, cap) for kind in STEMS}
    return table


def sha256_of(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def main():
    if not os.path.isdir(SRC):
        sys.exit(
            "no source sprites at %s -- run sync-shared.ps1 first (the FooterArt leg)" % SRC
        )

    table = read_cap_table()
    if len(table) != 22:
        sys.exit("expected 22 skins in theme.ts, parsed %d" % len(table))

    os.makedirs(DST, exist_ok=True)
    # Clear stale output, so a removed skin does not leave four orphans.
    for name in os.listdir(DST):
        if name.endswith(".png"):
            os.remove(os.path.join(DST, name))

    sprites, shapes, sources = {}, {}, {}
    for stem in STEMS:
        path = os.path.join(SRC, "footer-%s.png" % stem)
        if not os.path.exists(path):
            sys.exit("missing source sprite: %s" % path)
        sources[stem] = sha256_of(path)
        img = Image.open(path).convert("RGBA")
        sprites[stem] = np.array(img)
        shapes[stem] = fit_cap(sprites[stem])
        print("fitted %-8s %dx%d" % (stem, img.width, img.height))

    files, total = {}, 0
    for skin, caps in sorted(table.items()):
        for kind in STEMS:
            cap = caps[kind]
            baked = unpremultiply(
                reink(sprites[kind], shapes[kind], cap["top"], cap["glyph"])
            )
            im = Image.fromarray(baked, "RGBA").resize((OUTPUT_PX, OUTPUT_PX), Image.LANCZOS)
            im = im.quantize(colors=64, method=Image.FASTOCTREE)
            name = "%s-%s.png" % (skin, kind)
            out = os.path.join(DST, name)
            im.save(out, optimize=True)
            files[name] = sha256_of(out)
            total += os.path.getsize(out)

    manifest = {
        "note": (
            "Generated by scripts/bake-footer-caps.py. Do not hand-edit. "
            "capsManifest.test.ts holds this file, the baked PNGs, the source "
            "sprites and theme.ts's colour table to each other."
        ),
        "outputPx": OUTPUT_PX,
        "sourceSprites": sources,
        "colourTableSha256": hashlib.sha256(
            json.dumps(table, sort_keys=True).encode("utf-8")
        ).hexdigest(),
        "files": dict(sorted(files.items())),
    }
    io.open(MANIFEST, "w", encoding="utf-8", newline="\n").write(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )

    print(
        "baked %d caps -> %s (%d KB, avg %d B) at %dpx"
        % (len(files), DST, total // 1024, total // len(files), OUTPUT_PX)
    )


if __name__ == "__main__":
    main()
