# SNAPSHOT of H:\vscode-projects\HGapps\sync-shared.ps1 -- the live copy is there (unversioned).
# Committed here 2026-08-21 so the art-leg + site-mark notes survive; update when the live file changes.
# sync-shared.ps1 - refresh each repo's shared/ from the canonical HGapps\shared.
# Edit HGapps\shared (the master), then run this to push it into both repos.
#
# SCOPE IS DELIBERATELY NARROW (0.6.5, batch 4 phase 0). This used to be a
# single `robocopy $master $target /MIR` over the WHOLE shared\ tree, which
# became a loaded gun the moment the two sides stopped agreeing:
#
#   PR #10 (audit H12) deliberately deleted 271 files from
#   vinodex-ios\shared\newicons\ - the drawn-art masters were re-foldered into
#   vinodex-ios\art\, which is where every importer now reads them from. The
#   master here still carried those 271 files. A whole-tree /MIR would have
#   copied them straight back in, silently reverting H12 and dirtying a clean
#   repo with several hundred re-added binaries.
#
# So the mirror now enumerates exactly what is genuinely shared between the
# two apps, and touches nothing else:
#
#   data\        the TypeScript catalog (grapes, regions, styles, countries...)
#   services\    chip colours, entry utils - pure TS, zero dependencies
#   pixelflags\  the one art asset BOTH repos consume (ios rasterize-icons.sh,
#                web flagImages.ts), which is why it lives in the cross-repo
#                master rather than in vinodex-ios\art\ (iOS-only, and the web
#                repo cannot reach into it)
#   constants.ts types.ts stylePalette.ts
#
# NOT mirrored through shared\: drawn art masters. They live in
# vinodex-ios\art\ and are tracked in that repo. Adding a folder here means
# adding it to $Dirs below - a deliberate act, not a side effect of dropping
# files into shared\.
#
# ---------------------------------------------------------------------------
# THE WEB ART LEG (v6 ruling #2, 2026-08-18)
# ---------------------------------------------------------------------------
#
# The web renders a named subset of the drawn chrome art: the professor's six
# expressions, the passport stamps, the marquee panels, the skin stickers and
# the drawn button glyphs used by every large LCD tile.
# Those had no route into vinodex-web, so the web drew lucide glyphs instead.
#
# This leg is deliberately NOT a new folder under shared\, and that is the
# whole design. shared\ syncs into BOTH repos, so art placed there would land
# in vinodex-ios\shared\ as well - which is precisely the shape audit H12
# deleted (271 files under vinodex-ios\shared\newicons\). Instead this is a
# one-way leg: vinodex-ios (the owner) -> vinodex-web (the consumer). The
# masters in vinodex-ios\art\ are never touched, never copied, and never
# duplicated; ownership does not move.
#
# The SOURCE is the baked Resources rather than the masters. Those are the
# already-downscaled assets the iOS app itself renders (about 20 KB each
# against the masters' 157 KB), so one bake serves both platforms and the two
# apps draw pixel-identical chrome. It is the same arrangement web\public\
# icons\ has always had with Resources\Icons\, stated in LocalIcon.tsx.
#
# ENUMERATED, one line per directory, exactly like $Dirs above. A new art
# folder reaching the web is an edit here and nowhere else.
#
# NOTE the /MIR below is scoped to *.png inside each named target, so it also
# mirrors DELETIONS: a PNG authored on the web side and dropped into one of
# these named folders is removed by the next sync. That is what /MIR is for and
# it is why the leg is enumerated rather than aimed at all of web\public\art.
$WebArt = @(
    @{ From = 'VinoArt';    To = 'vino'    },  # 6  the professor's expressions
    @{ From = 'StampArt';   To = 'stamp'   },  # 10 passport stamps
    @{ From = 'MarqueeArt'; To = 'marquee' },  # 36 per-route marquee panels
    @{ From = 'StickerArt'; To = 'sticker' },  # 20 chassis skin stickers
    @{ From = 'FooterArt';  To = 'footer'  },  # 4  the drawn moulded caps
    @{ From = 'ButtonArt';  To = 'button'  }   # 31 large LCD button glyphs
)

# NOTE on the footer caps, because the /MIR above makes it a trap.
#
# web\public\art\footer\ holds the FOUR SOURCE SPRITES and nothing else.
# The web bakes 88 per-skin variants from them (22 skins x 4 caps), and
# those live in web\public\art\caps\ - deliberately NOT a folder in the
# list above. If the baked output were written into art\footer\ the next
# sync would delete all 88 of them, because /MIR mirrors deletions and the
# source side has only four files. Keep the two directories apart.

# NOTE on web\public\art\site\, which is the SAME trap from the other side.
#
# That folder holds the ONE piece of art the web draws for itself:
# marquee-horizon-godot.png, the company site's marquee mark, generated by
# vinodex-web\scripts\draw-site-marquee.py. iOS has no company site, so it
# has no mark for one and never will - there is nothing upstream to mirror.
#
# It is deliberately NOT listed as a target in the table above. A
# web-authored PNG dropped into web\public\art\marquee\ would be deleted by
# the very next sync, silently: /MIR removes anything the iOS side lacks,
# nothing fails, and the site quietly falls back to the encyclopedia's
# wineglass glyph. Same reasoning as the caps note above, opposite side.
#
# vinodex-web\web\src\services\siteMarquee.test.ts reads THIS table and
# fails if 'site' is ever added to it - and fails if this note disappears.

$ErrorActionPreference = 'Stop'
$HG = $PSScriptRoot
$master = Join-Path $HG 'shared'
if (-not (Test-Path $master)) { Write-Host "No master at $master" -ForegroundColor Red; exit 1 }

# Directories mirrored with /MIR - scoped per-folder, so a deletion inside one
# of these propagates (that is the point) while everything outside them is
# left alone.
$Dirs  = @('data', 'services', 'pixelflags')
# Loose files copied only if changed.
$Files = @('constants.ts', 'types.ts', 'stylePalette.ts')

$targets = @(
    (Join-Path $HG 'vinodex-web\shared'),
    (Join-Path $HG 'vinodex-ios\shared')
)

$missing = @()
foreach ($t in $targets) {
    Write-Host "Syncing -> $t"
    foreach ($d in $Dirs) {
        $src = Join-Path $master $d
        if (-not (Test-Path $src)) { $missing += $d; continue }
        robocopy $src (Join-Path $t $d) /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
        # robocopy exit codes 0-7 are success (8+ is a real failure).
        if ($LASTEXITCODE -ge 8) { Write-Host "  robocopy failed for $d (exit $LASTEXITCODE)" -ForegroundColor Red; exit 1 }
    }
    foreach ($f in $Files) {
        $src = Join-Path $master $f
        if (-not (Test-Path $src)) { $missing += $f; continue }
        Copy-Item $src (Join-Path $t $f) -Force
    }
}

# The web art leg. Source and target are both explicit; nothing here reads or
# writes shared\, and nothing here touches vinodex-ios.
$artSrcRoot = Join-Path $HG 'vinodex-ios\Sources\VinodexUI\Resources'
$artDstRoot = Join-Path $HG 'vinodex-web\web\public\art'
if (Test-Path $artSrcRoot) {
    Write-Host "Syncing web art -> $artDstRoot"
    foreach ($a in $WebArt) {
        $src = Join-Path $artSrcRoot $a.From
        if (-not (Test-Path $src)) { $missing += ('art-' + $a.From); continue }
        robocopy $src (Join-Path $artDstRoot $a.To) *.png /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
        if ($LASTEXITCODE -ge 8) { Write-Host ("  robocopy failed for " + $a.From + " (exit $LASTEXITCODE)") -ForegroundColor Red; exit 1 }
    }
} else {
    Write-Host "No vinodex-ios Resources at $artSrcRoot - web art leg skipped." -ForegroundColor Yellow
}

if ($missing.Count -gt 0) {
    Write-Host ("Not in master, skipped: " + (($missing | Select-Object -Unique) -join ', ')) -ForegroundColor Yellow
}
Write-Host "Shared synced." -ForegroundColor Green
Write-Host "Next: in vinodex-ios run 'npm run generate' and commit if Resources/*.json changed;"
Write-Host "      commit the updated shared/ in each repo."
